# Site settings
title: Tempat Wisata Terbaik
header-img: img/home-bg.jpg
email: cahbetik@yahoo.com
copyright_name: Your/Project/Corporate Name
description: "Beragam tempat wisata terbaik di dunia"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://adiba.github.io/"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  cahbetik@yahoo.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
